### ISSUE TITLE
Roulette doesn't reset upon respawning

### ISSUE THREAD

**Issue by hayaunderscore** [minenice55/xItemLib#20]
The effect where the roulette seems to stop when you just died also seems to be nonexistent.

With xItemLib
https://github.com/minenice55/xItemLib/assets/126386046/c56a3d02-6af0-4406-a4da-355d3bbcfc2f

Without xItemLib
https://github.com/minenice55/xItemLib/assets/126386046/cd4770b2-cce2-4766-8585-664a146ec7e5

**Comment by minenice55** [comment]
I forgot that's how this game worked lol I'll get that fixed
