### ISSUE TITLE
Cutout items are picked up regardless of held item

### ISSUE THREAD

**Issue by Bladesinger24** [minenice55/xItemLib#23]
Players are able to "pick up" a cutout item regardless of what they are currently carrying. Picking up cutout items that match your current item continues to work as expected.

Version used:
v112r5

Example of the bug:
https://imgur.com/0tW12EH

**Comment by minenice55** [comment]
can't seem to replicate, would this happen to be a mod conflict?
![kart0023](https://github.com/minenice55/xItemLib/assets/43734252/554ef387-af94-4987-a64b-ac6ba0fa4b69)

**Comment by Bladesinger24** [comment]
What version is that in the gif? I've checked all our addons (xItemLib_v112r5.lua), downloaded the xItem lua on this github (xItemLib_v112.lua) and even tried the standalone of xItem on the MB (xItemLib_v112r5.lua), all still produced the same issue

EDIT: All of the addons were loaded by themselves
EDIT 2: And on an unaltered instance of SRB2K
